service: type-graphql-demo

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    host: 0.0.0.0
    port: 3000

provider:
  name: aws
  runtime: nodejs8.10

functions:

  graphql:
    handler: src/main.graphql
    events:
      - http:
          method: post
          path: graphql

  playground:
    handler: src/main.playground
    events:
      - http:
          method: get
          path: playground